name: api_request_helper_flutter
description: Api Request Helper Flutter is a repository that handles http calls such as GET, POST, PUT, DELETE
version: 1.2.1+9
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  exceptions_flutter:
    git:
      url: https://github.com/ChargePlus/exceptions_flutter.git
  flutter:
    sdk: flutter
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
